// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.TextLemmatizer
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("found")]
        public long Found { get; set; }

        [JsonProperty("lemmas")]
        public Lemmas Lemmas { get; set; }
    }

    public partial class Lemmas
    {
        [JsonProperty("cat")]
        public long Cat { get; set; }

        [JsonProperty("ran")]
        public long Ran { get; set; }

        [JsonProperty("door")]
        public long Door { get; set; }
    }
}
